### ISSUE TITLE
PEM helpers to generate easiy a key pair programatically?

### ISSUE THREAD

**Issue by chibenwa** [Hakky54/sslcontext-kickstart#115]
**Is your feature request related to a problem? Please describe.**

As discussed in this email on the James mailing list https://www.mail-archive.com/server-dev@james.apache.org/msg70783.html we are considering adding on-the-fly generation for SSL cryptographic materials as an option.

The goal being to conciliate two requirements:

  - Not shipping default keys - administrators NOT updating the default configuration would be trivially exposed to man-in-the-middle attacks...
  - But at the same time have one signle command startup (`docker run ...`)
  
One solution being on the fly key generation.

**Describe the solution you'd like**

I would enjoy having methods in PEM util (or another one) to create such keys / KeyManager...

**Describe alternatives you've considered**

Specifying a startup script in the dockerfile creating the keys if missing. Could work too.

Suitable for my demo image where I already have a bash wrapper in place ( https://github.com/apache/james-project/pull/628 contributes it) yet making it more generic to the other production grade docker image can not rely on this approach but might benefit from this 'feature' - for instance people could try the Distributed James docker compose in a single `docker-compose up` command.

**Additional context**

James ticket: https://issues.apache.org/jira/browse/JAMES-3640

**Comment by Hakky54** [comment]
So you basically don't want to include default pem based private keys for security reasons and to make your docker script more convenient. If I understand it correctly you want to generate the keypair programatically on the fly and this could be a self signed one right?

I think this is possible within this library, but there is already a good existing project which can do this. This project might be interesting for you: https://github.com/tersesystems/securitybuilder Their documentation is also good which makes it easy to use. You can build keypair, certificatechain or other ssl materials with their fluent-api builders. Please let me know if this is something which would work for you or else we can still add the feature what you are looking for in this library.

**Comment by chibenwa** [comment]
> If I understand it correctly you want to generate the keypair programatically on the fly and this could be a self signed one right?

Right :-)

> I think this is possible within this library, but there is already a good existing project which can do this. This project might be interesting for you: https://github.com/tersesystems/securitybuilder Their documentation is also good which makes it easy to use. You can build keypair, certificatechain or other ssl materials with their fluent-api builders.

That's awesome, huge thanks!

> Please let me know if this is something which would work for you or else we can still add the feature what you are looking for in this library.

I'm likely not working on this anytime soon - I have something up for the demo, the others can wait (I guess... Sometime I am mistaken with such guesses ^^ ) but I will definitely read and save the pointer to that project for later :-)

**Comment by chibenwa** [comment]
(Feel free to close this issue as it might not make sense to this project BTW :-) )

**Comment by Hakky54** [comment]
Yess, indeed let's close it. Good luck with the demo and with the other PR in James! If you need any help you can join the gitter channel or open a new issue here.
