### ISSUE TITLE
Remove/Disable logging in unsafe HostnameVerifier and TrustManager

### ISSUE THREAD

**Issue by dasteg** [Hakky54/sslcontext-kickstart#121]
the logging in the unsafe variants of HostnameVerifier and TrustManager spam logs. There should be a way to disable this or at least log it to DEBUG.

I see no reason why i would like to know that a self signed certificate is trusted. that's exactly what i want to do else i wouldn't use this specific verifier.

**Comment by Hakky54** [comment]
The changes will be available at version 7.0.2 today
