### ISSUE TITLE
About the purpose of Webflux

### ISSUE THREAD

**Issue by HelloTo4x** [Hakky54/sslcontext-kickstart#186]
Hi, i am reading your project, can u tell me the purpose of Webflux, reactive in your project ? Is it for increasing performance, can u tell me some disadvantaged of Webflux ?

**Comment by Hakky54** [comment]
I have added webflux to my project to provide developers an example on how to use this library with webflux. For the advantages and disadvantages I would recommend to check out stackoverflow, bealdung, YouTube and other resources as that is a better place to learn more about webflux. This issue page is for discussing issues, features and bugs related to this library. Therefore I am closing this issue. Feel free to open a new issue if it is related to this library

**Comment by HelloTo4x** [comment]
I know, can u tell me the purpose of Reactive in your project

**Comment by Hakky54** [comment]
The purpose was to just demonstrate how this library can be configured with webflux for other developers. Also as a cheatsheet. And next to that i think is important to provide a working example/demo to proof that the library works good with different http clients including webflux.
