### ISSUE TITLE
Simplify use of system truststore

### ISSUE THREAD

**Issue by charphi** [Hakky54/sslcontext-kickstart#19]
Under Windows and MacOS, it is possible to use the system truststore in addition to regular keystores.
With the current library, it can be achieved by a code like this:
```java
SSLFactory.Builder result = SSLFactory
                .builder()
                .withDefaultTrustMaterial();
if (isWindows()) {
  KeyStore root = KeyStore.getInstance("Windows-ROOT");
  root.load(null, null);
  result.withTrustMaterial(root, new char[0]);
  KeyStore my = KeyStore.getInstance("Windows-MY");
  my.load(null, null);
  result.withTrustMaterial(my, new char[0]);
} else if (isMacos()) {
  KeyStore keychain = KeyStore.getInstance("KeychainStore");
  keychain.load(null, null);
  result.withTrustMaterial(keychain, new char[0]);
}
```
I would prefer to have something like:
```java
SSLFactory.Builder result = SSLFactory
                .builder()
                .withDefaultTrustMaterial()
                .withSystemTrustMaterial();
```

**Comment by Hakky54** [comment]
Hi Philippe,

That's quite interesting. I wasn't aware that we could grab the system trust material in that way.
The current workaround doesn't look very charming indeed, let me try to include this in the library. Thank you by the way for suggestion this!

**Comment by Hakky54** [comment]
@charphi 

It is available within version 5.1.0
Let me know if this solution works for your needs

**Comment by charphi** [comment]
I've just tested and it works properly. Thanks.

**Comment by Hakky54** [comment]
Hi @charphi with version 8.1.2 we have now support for additional windows system keystores, see here for the details: https://github.com/Hakky54/sslcontext-kickstart/blob/021d50406ed1d55e8977f9a7446163549abefbef/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/KeyStoreUtils.java#L228

**Comment by charphi** [comment]
Excellent, thank you !
I was not aware of these new keystores.
