### ISSUE TITLE
BasicHostnameVerifier is broken?

### ISSUE THREAD

**Issue by swankjesse** [Hakky54/sslcontext-kickstart#210]
It appears that BasicHostnameVerifier doesn't actually check that the hostname in the URL matches the hostname in the SAN part of the peer’s certificate.

As a consequence, a server that had a certificate for say `attacker.com` could be verified against a client request to `victim.com`.

**Comment by Hakky54** [comment]
Thank you Jesse for you remark. I was not aware of that.
I will make sure to improve the validation of the hostname. But if you want, you can also open a PR as it seems like you have some knowledge on that area

**Comment by Hakky54** [comment]
Hi @swankjesse 

I found out why I didn't created an advanced hostname verifier back then. Two years ago I came across this stackoverflow answer: https://stackoverflow.com/a/64391583/6777695 which stated the following:

> As the comments at the top say, that class is no longer used; it was the abstract user-visible class that is now replaced by [javax.net.HttpsURLConnection](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/javax/net/ssl/HttpsURLConnection.java) which you will observe has the same code. But the _implementation_ class for https URL is [sun.net.www.protocol.https.HttpsURLConnectionImpl](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/net/www/protocol/https/HttpsURLConnectionImpl.java) which just wraps (delegates to) [sun.net.www.protocol.https.DelegateHttpsURLConnection](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/net/www/protocol/https/DelegateHttpsURLConnection.java) which subclasses [sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/net/www/protocol/https/AbstractDelegateHttpsURLConnection.java) which to make the actual connection uses [sun.net.www.protocol.HttpsClient and in particular .afterConnect()](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/net/www/protocol/https/HttpsClient.java#L426). As background, in earlier versions of Java `SSLSocket` did not do hostname verification, so the implementation of HttpsURLConnection had to add it. In Java 7 up, `SSLSocket` does support 'endpoint identification', so when afterConnect() recognizes that the hostnameVerifier on this URLconnection was the default one, it turns off `needToCheckSpoofing` and sets the `SSLSocket` to do endpoint identification.
>
> [javax.net.ssl.SSLSocket](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/javax/net/ssl/SSLSocket.java) is similarly an abstract class that is actually implemented by [sun.security.ssl.SSLSocketImpl](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/javax/net/ssl/SSLSocket.java) and several dozen related classes including [sun.security.ssl.ClientHandshaker.serverCertificate()](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/security/ssl/ClientHandshaker.java#L1297) which calls the configurable trustmanager which by default is [sun.security.ssl.X509TrustManagerImpl](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/security/ssl/X509TrustManagerImpl.java) which in [checkTrusted()](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/security/ssl/X509TrustManagerImpl.java#L250) since endpoint identification was requested calls [checkIdentity()](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/security/ssl/X509TrustManagerImpl.java#L337) which calls [sun.security.util.HostnameChecker](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/security/util/HostnameChecker.java) with TYPE_TLS (actually meaning HTTPS RFC 2818), and _that_ does the actual checking.
>
> Glad you asked?
>
> PS: the analysis on that webpage, that HttpsURLConnection.DefaultHostnameVerifier is called only for mismatch, is quite wrong. As above it is bypassed and _never_ called by the actual implementation. 
>
> Also I assume you realize java 7 has not been supported for years unless you pay. Although _this_ area hasn't changed that I know of in more recent versions. Java 11 does add a new java.net.http.HttpClient which functionally supersedes [Http,Https]URLConnection. 

So I concluded back then that any http client which uses a trustmanager will have by default `endpoint identification`. So the trustmanager is taking care of the endpoint identification. I am curious, why did OkHttp still have a custom hostname verifier?

I sort of feel like I know the answer. The endpoint identification in the hostname verifier of OkHttp is much more advanced/secure than the endpoint identification in the default jdk trustmanager, is that right?

**Comment by swankjesse** [comment]
Ummm, I don't really know too much about that! But I believe you really do need a real hostname verifier everywhere.
