### ISSUE TITLE
Easy way to specify KeyManagerFactory type (PKIX instead of SunX509)

### ISSUE THREAD

**Issue by ecki** [Hakky54/sslcontext-kickstart#235]
**Is your feature request related to a problem? Please describe.**
I want to use the New (PKIX) Key Manager (instead of SunX509) for some client auth Keystores. Currently I use factory.withIdendityMaterial(keystore) which internally uses the default KeyStoreManager (which defaults to the SunX509 legacy manager).

**Describe the solution you'd like**
Adding a `withIdendityMaterial(KeyStore ks, String keyManagerType)` or allowing to configure the default would help.

**Describe alternatives you've considered**
There are alternatives using the `withIdendityMaterial(KeyManager p)`, but that requires two utility calls to get a Keystore and a KeyManager first. Is that the intended way?

**Comment by Hakky54** [comment]
Hi @ecki 

I like your suggestion, i would prefer the first suggestion of having overloaded methods where we can provide the keymanager factory algorithm as a parameter. It will be more in sync with the other methods. 

Your own alternative of having to call two methods works indeed but it will make it a bit more verbose as we can hide the verbosity within the library. Feel free to create a PR if you want, or else i can add it tomorrow.

By the way, if you have other good suggestions keep them coming!

**Comment by ecki** [comment]
I can do that, but I am not sure for which parameter combinations (InputStream, Path, w/ and w/o KeystoreProvider) and also do you also want to configure the KeyManager provider? Currently I need it only for the withIdendityMaterial(KeyStore, char[]) variant with default provider.

I wonder if a option interface would meybe better:

    builder().setOption(NEW_KEYMANAGER).withIdendityMaterial(path, char[], char[], "JKS").build()

instead?

**Comment by Hakky54** [comment]
Adding new (overloaded) methods having the additional parameter for KeyManagerFactoryAlgorithm was what I preferred , but looking at the current state of the SSLFactory I see couple of issues. The methods will become in my opinion too complicated by having too much arguments. Next to that it will also be verbose if someone wants to add multiple different keystores having the same  KeyManagerFactoryAlgorithm. They need to repeat it by providing the KeyManagerFactoryAlgorithm everytime when they want to add any identity material.

I like your suggestion of setting an option, that would simplify the usage and reduce the verbosity. I would however prefer a name which is more explicit. Option is a bit generic in my opinion. What do you think of `withIdentityMaterialOptions` and `withTrustMaterialOptions`?

So my suggestion would be:
```
SSLFactory.builder()
    .withIdendityMaterial(path, char[], char[], "JKS")
    .withIdentityMaterialOptions("PKIX")
    .build()
```

The method could have the following signature:
```
public Builder withIdentityMaterialOptions(String keyManagerFactoryAlgorithm) {
    
}
```

Looking forward to your implementation

**Comment by ecki** [comment]
Yes Sounds good to make it specific. In that Case maybe withIdendityMaterialManager(String[, String) or (KeyManagerFactory) or (String, Provider)?

Will that be a global option, or only apply to all following Idendity material (or to all not yet configured)?

I think setting it before adding Idendity material and allowing to be set different ones would be most flexible (but not necessarily the easiest to use)

    builder().withIMManager("PKIX","SunJSSE").withIM(jks)
             .withIManager("SunX509"/*,default*/).withIM(key)

everything added before the first withIdendityMaterialManager() would use the KeyManager.getDefaultType() like before.

**Comment by Hakky54** [comment]
You could use the following option as provider object or name if it is set. It is already present in the current source code, so you could easily use that instead of having an additional parameter in `withIdentityMaterialOptions`.
https://github.com/Hakky54/sslcontext-kickstart/blob/5c41a8ee4076eca5306a3d34424e974477cae51c/sslcontext-kickstart/src/main/java/nl/altindag/ssl/SSLFactory.java#L176

```
SSLFactory.builder()
        .withIdentityMaterial(Paths.get("/path/to/your/identity.jks"), "password".toCharArray(), "JKS")
        .withIdentityMaterialOptions("PKIX")
        .withSecurityProvider("SunJSSE")
        .build();
```

I would prefer it as a global variable, in that way it can be applied to all of the keystores. It will be easier to use, without the end-user needing to know how to properly use it as there would be just one way to use it.
