### ISSUE TITLE
Provide method to set default Truststore

### ISSUE THREAD

**Issue by balbusm** [Hakky54/sslcontext-kickstart#250]
**Is your feature request related to a problem? Please describe.**
I was trying to add Truststore to all SSLContext that will be used in the app
Currently this lib requires manual injection of SSLContext into all connection libraries to achieve it.
It's cumbersome when there are few higher level libraries that are using different connection libraries under the hood (eg Apache and OkHttp).

**Describe the solution you'd like**
It would be good to set single TruststoreFactory (or SSLContext factory) that will generate desired objects.

**Additional context**
I created a simple TrustManagerFactory that provides TrustManagers. 
I would be good to have this functionality out of the box in this lib.

```
public class SingletonTrustManagerFactorySpi extends TrustManagerFactorySpi {

    private static TrustManager[] trustManagers;

    public static void setTrustManager(TrustManager aTrustManager) {
        trustManagers = new TrustManager[]{aTrustManager};
    }

    @Override
    protected void engineInit(KeyStore keyStore) {
        log.info("Ignoring provided keystore to SingletonTrustManager");
    }

    @Override
    protected void engineInit(ManagerFactoryParameters managerFactoryParameters) {
        log.info("Ignoring provided ManagerFactoryParameters");
    }

    @Override
    protected TrustManager[] engineGetTrustManagers() {
        return trustManagers;
    }
}
public class SingletonTrustManagerFactoryProvider extends Provider {

    public SingletonTrustManagerFactoryProvider() {
        super("TrustManagerFactoryProvider", 1.0, "Provides TrustManagerFactory");
        Service service = new Service(this,
                "TrustManagerFactory",
                "PKIX",
                SingletonTrustManagerFactorySpi.class.getName(),
                ImmutableList.of("SunPKIX", "X509", "X.509"),
                Collections.emptyMap());
        putService(service);
    }
}
```
This method should be available in TrustManagerUtils
```
    public void setDefaultTrustManager(TrustManager trustManager) {
        SingletonTrustManagerFactorySpi.setTrustManager(trustManager);

        ProviderList providerList = ProviderList.insertAt(Providers.getProviderList(),
                new SingletonTrustManagerFactoryProvider(), 0);
        Providers.setProviderList(providerList);
    }
```

**Comment by Hakky54** [comment]
Hi @balbusm 

Can you demonstrate how you use this library currently with your use case?

**Comment by balbusm** [comment]
I use this library to load custom certificate and keep default certificates,
then I set default truststore manager.
See below example snippet:
```
X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial(Paths.get(truststorePath));
SSLFactory sslFactory  = SSLFactory.builder()
                .withDefaultTrustMaterial()
                .withTrustMaterial(trustManager)
                .build();

X509ExtendedTrustManager trustManager = sslFactory.getTrustManager().get();

setDefaultTrustManager(trustManager);
```

**Comment by Hakky54** [comment]
What happens inside the `setDefaultTrustManager` method?

I am also trying to understand what the issue is you are currently facing and how your suggestion in the initial post of this issue will resolve it. What are you trying to resolve with your suggestion?

**Comment by balbusm** [comment]
`setDefaultTrustManager` is shown in the initial description.
Problem:
I have custom certificate that needs to be trusted along with default certificates. 
In my code there are 2 libraries used to connect to 3 hosts. (One of those libraries is [Influx java client](https://github.com/influxdata/influxdb-client-java) )
Two of those hosts are using custom certificate.

Current state:
To provide custom certificates along with default certificates 
I have to find out what HTTP client is used by 3rd party library,
read your instruction how to inject SSLContext to HTTP client,
find out how to inject SSLContext into 3rd party library (eg how to inject SSLContext into Inlfux client)
Repeat those steps with another library.

Solution:
To avoid those steps my proposal is to create custom truststore and return it every time Java tries to create new truststore.

**Comment by Hakky54** [comment]
Maybe I am missing something. I have the idea that everything what you need is already available within the library. So I am not able to understand why you would need a TrustManagerFactorySpi and a custom Provider from the TrustManagerFactory and add that to the provider list...
 
Influx java client can be easily configured with the OkHttp client and Apache Http client can also easily configured. Buth of the client are compatible with the current version of this library and provides all of the required objects to configure it with ssl.

Lets assume you have the following SSLFactory:

```java
X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial(Paths.get(truststorePath));
SSLFactory sslFactory  = SSLFactory.builder()
                .withDefaultTrustMaterial()
                .withTrustMaterial(trustManager)
                .build();
```

### InfluxDB
```java
OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder()
        .sslSocketFactory(sslFactory.getSslSocketFactory(), sslFactory.getTrustManager().orElseThrow())
        .hostnameVerifier(sslFactory.getHostnameVerifier());

InfluxDB influxDB = InfluxDBFactory.connect(databaseURL , userName, password, httpClientBuilder);
```

### Apache Http Client
Apache has four commonly used Http Clients, I am not sure which one you are using so I will provide all of them here:

####
```java
LayeredConnectionSocketFactory socketFactory = Apache4SslUtils.toSocketFactory(sslFactory);

HttpClient httpClient = HttpClients.custom()
        .setSSLSocketFactory(socketFactory)
        .build();

**Comment by Hakky54** [comment]
Maybe I am missing something. I have the idea that everything what you need is already available within the library. So I am not able to understand why you would need a TrustManagerFactorySpi and a custom Provider from the TrustManagerFactory and add that to the provider list...

Influx java client can be easily configured with the OkHttp client and Apache Http client can also easily configured. Buth of the client are compatible with the current version of this library and provides all of the required objects to configure it with ssl.

Lets assume you have the following SSLFactory:

```java
X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial(Paths.get(truststorePath));
SSLFactory sslFactory  = SSLFactory.builder()
                .withDefaultTrustMaterial()
                .withTrustMaterial(trustManager)
                .build();
```

### InfluxDB
```java
OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder()
        .sslSocketFactory(sslFactory.getSslSocketFactory(), sslFactory.getTrustManager().orElseThrow())
        .hostnameVerifier(sslFactory.getHostnameVerifier());

InfluxDB influxDB = InfluxDBFactory.connect(databaseURL , userName, password, httpClientBuilder);
```

### Apache Http Client
Apache has four commonly used Http Clients, I am not sure which one you are using so I will provide all of them here:

#### Apache HttpClient 4
```java
LayeredConnectionSocketFactory socketFactory = Apache4SslUtils.toSocketFactory(sslFactory);

HttpClient httpClient = HttpClients.custom()
        .setSSLSocketFactory(socketFactory)
        .build();
```
#### Apache Async HttpClient 4
```java
CloseableHttpAsyncClient client = HttpAsyncClients.custom()
        .setSSLContext(sslFactory.getSslContext())
        .setSSLHostnameVerifier(sslFactory.getHostnameVerifier())
        .build();

client.start();
```

#### Apache HttpClient 5
```java
HttpClientConnectionManager connectionManager = PoolingHttpClientConnectionManagerBuilder.create()
        .setSSLSocketFactory(Apache5SslUtils.toSocketFactory(sslFactory))
        .build();

HttpClients.custom()
        .setConnectionManager(connectionManager)
        .build();
```

#### Apache Async HttpClient 5
```java
AsyncClientConnectionManager connectionManager = PoolingAsyncClientConnectionManagerBuilder.create()
        .setTlsStrategy(Apache5SslUtils.toTlsStrategy(sslFactory))
        .build();

CloseableHttpAsyncClient client = HttpAsyncClients.custom()
        .setConnectionManager(connectionManager)
        .build();

client.start();
```

Can you try this out and tell me if it works for you?

**Comment by balbusm** [comment]
My point here is configuring each HTTP client is cumbersome.
You need to know what HTTP client is used under the hood and figure out how to inject SSLContext into the library.
If library changes it's HTTP client code won't work.
The solution that I'm proposing is to replace snippets that you provided by single line of code where default TrustManager is set.

**Comment by Hakky54** [comment]
Yes, I now understand your point. I tried it out with 50 different http clients and it indeed works for most of them, in my case it passed with 46 clients. I was not aware of this kind of functionality. I always thought that the client needs to be explicitly configured with the ssl configuration like supplying the sslcontext, trustmanager, keymanager etc. With this kind of option it would indeed make it much easier to configure a http client with ssl without explicitly configuring it...

Any idea whether this is also possible for the keymanager, cipher suites, ssl protocols, hostname verifier?

By the way, do you have any documentation regarding the configuration for the ProviderList and how it automatically picks up the trustmanager from the securty provider?

Thank you by the way for suggesting this setup, it is amazing and I appreciate your contribution! It took some time to understand it.

**Comment by balbusm** [comment]
It's also possible with all security components including SSLContext.
General idea is that those providers works like factories for security components.
ProviderList picks up first provider that matches requested type, algorithm and provider.
See sun.security.jca,GetInstance.getService method

Link to the documentation:
https://docs.oracle.com/javase/9/security/howtoimplaprovider.htm#JSSEC-GUID-B35E3749-0A12-42C3-BA0B-C444D7E140BB
Something similar BouncyCastle is doing:
https://github.com/bcgit/bc-java/blob/master/tls/src/main/java/org/bouncycastle/jsse/provider/BouncyCastleJsseProvider.java

I'm happy to hear you find it useful.

**Comment by Hakky54** [comment]
By the way @balbusm I discovered that the code snippet below also works instead of setting a default trustmanager via the provider,. Your SSLFactory configuration:
```java
X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial(Paths.get(truststorePath));
SSLFactory sslFactory  = SSLFactory.builder()
                .withDefaultTrustMaterial()
                .withTrustMaterial(trustManager)
                .build();
```

```java
SSLContext.setDefault(sslFactory.getSslContext());
```

Can you try it on your side and tell me if that also works for you?

**Comment by Hakky54** [comment]
> During the testing I discovered the configuration for the trustmanager works with 95% and the keymanager works with 30% of the tested http clients. I used my other repo for testing all of the http clients, which can be found here: https://github.com/Hakky54/mutual-tls-ssl#tested-clients The configuration in this PR is correct, however a-lot of http clients won't pick it up. Next to that it messes op the initialization of a new KeyManagerFactory/TrustManagerFactory when you need a new one for example when someone tries to reload the ssl configuration. I like the idea of configuring the ssl configuration globally, but sadly it does not work with all of the http clinets which is for me a no-go and next to that it will break other functionalities. Therefor I am closing the PR and issue. Thank you for creating the feature request and sharing your knowledge @balbusm !
