### ISSUE TITLE
Heads up, thank you for this gem!

### ISSUE THREAD

**Issue by EugenMayer** [Hakky54/sslcontext-kickstart#253]
Just wanted to thank you for making and maintaining this little gem here.

Very flexible with that build and solves basically all scenarios i could think of.  Please take my credits :)

**Comment by Hakky54** [comment]
Thank you very much for your kind words Eugen! I was very happy to see your comment here 😄 
I am always curious how others are using it as it contains multiple utilities, which part of the library are you using and how are you using it, and how did you find this library? 

Do you think something can be improved, missing features, maybe some missing methods, better describing methods or do you think the readme can be improved or was it clear enough?

**Comment by EugenMayer** [comment]
We are configuring the apache ldap client. Easier to share code

```java
  var sslBuilderFactory = SSLFactory.builder();
    if (!VERIFY_CERTIFICATE) {
      // no verification at all, allow all
      sslBuilderFactory.withUnsafeTrustMaterial();
    }
    else {
      // add system ca-certificates to support official certificates
      sslBuilderFactory
        .withDefaultTrustMaterial()
        .withSystemTrustMaterial();
    }

    // if a certificate is given, add it as a valid certificate to the store
    if (Strings.isNotBlank(serverConfiguration.getCertificate())) {
      InputStream certInputStream = IOUtils.toInputStream(serverConfiguration.getCertificate(), StandardCharsets.UTF_8);
      Certificate certificate = CertificateFactory.getInstance("X.509").generateCertificate(certInputStream);
      sslBuilderFactory.withTrustMaterial(certificate);
    }

    return sslBuilderFactory.build().getTrustManagerFactory().orElseThrow().getTrustManagers();
```

I think the docs and the builder is more then good enough. We are covering 4 cases here alone, replacing a much more bigger part that covered only 4.

From my side, super happy!

**Comment by Hakky54** [comment]
It looks pretty compact, nice! I think you can even further refactor it. What do you think of the following snippet:

```java
var sslBuilderFactory = SSLFactory.builder();
if (!VERIFY_CERTIFICATE) {
    // no verification at all, allow all
    sslBuilderFactory.withUnsafeTrustMaterial();
}
else {
    // add system ca-certificates to support official certificates
    sslBuilderFactory
            .withDefaultTrustMaterial()
            .withSystemTrustMaterial();
}

// if a certificate is given, add it as a valid certificate to the store
if (Strings.isNotBlank(serverConfiguration.getCertificate())) {
    sslBuilderFactory.withTrustMaterial(CertificateUtils.loadCertificate(serverConfiguration.getCertificate()));
}

return sslBuilderFactory.build().getTrustManagers().orElseThrow();
```

I have replaced the codesnippet of apache IOUtils for creating an inputstream and the usage of the Certificatefactory with CertificateUtils which is capapble of doing the same under the covers. And next to that I noticed you are getting the TrustManager from the TrustManagerFactory but you can also get it directly from the SSLFactory.

**Comment by EugenMayer** [comment]
Nice! Thank you so much, there is even more to it. Lovely!

**Comment by EugenMayer** [comment]
@Hakky54 
```java
sslBuilderFactory.build().getTrustManagers().orElseThrow();
```
does not work for me, `getTrustManagers` is not a method on `SSLFactory` - using 7.4.8 (non netty) version. 

Also since i want to know when the certificate is invalid ( user input ), thus rely on `CertificateException`, i rather stick with my loading code, even though it is far less elegant. Special case on my side here

**Comment by Hakky54** [comment]
My bad, I made a typo it should be `sslBuilderFactory.build().getTrustManager().orElseThrow();` however this method returns a X509ExtendedTrustManager while with your original code snippet it returned `TrustManager[]`. Not quite sure which one fits your needs
