### ISSUE TITLE
Request support check general key with tools PemUtils

### ISSUE THREAD

**Issue by nguyentthai96** [Hakky54/sslcontext-kickstart#276]
//X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial("<path_key>");
X509ExtendedKeyManager keyManager = PemUtils.loadIdentityMaterial("path_key_cer", "path_client_key", "scretKeyPass");
SSLFactory sslFactory = SSLFactory.builder()
        .withTrustMaterial(trustManager)
        .withIdentityMaterial(keyManager)
        .build();

SSLFactory sslFactory = SSLFactory.builder()
                    .withIdentityMaterial(keyManager)
                    //.withTrustMaterial(trustManager)
                    .build();

URL wsURL = new URL(urlServer);
HttpsURLConnection httpsConn = (HttpsURLConnection) wsURL.openConnection();
                    httpsConn.setSSLSocketFactory(sslFactory.getSslSocketFactory());

Hi [sslcontext-kickstart] I using your tools to load key for client site call request, Now I want config a nginx proxy to handler redirect request other server, I can change config urlServer in olds server, and key path_key, path_key_cer, path_client_key, but now I cannot change code server old. How any solution config nginx with key tool PemUtils.loadIdentityMaterial;

2023/01/31 13:44:32 [info] 32#32: *4 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.17.0.1, server: 0.0.0.0:443

I have try some solution but cannot https://egkatzioura.com/2021/09/24/add-ssl-to-nginx/;
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Hakky54** [comment]
Hi, can you retry with the following VM arguments: `-Djavax.net.debug=SSL,keymanager,trustmanager,ssl:handshake`

It will give more detailed message of the ssl handshake. Can you copy and paste it here?

So basically you are trying to configure nginx with ssl and nginx sends the requests to to server. You are trying to connect with your client, in this case with the HttpsURLConnection, but it fails right?

**Comment by nguyentthai96** [comment]
Hi Mr. , I attack file debug ssl 
[ssl_debug_20230201.log](https://github.com/Hakky54/sslcontext-kickstart/files/10552827/ssl_debug_20230201.log)



And script config of nginx:

server {
    error_log /var/log/nginx/error.log debug;
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name me.mask.domain;

    ssl_password_file /etc/nginx/certs/passphrase;
    #ssl_certificate /etc/nginx/certs/ca.crt;
    #ssl_certificate_key /etc/nginx/certs/ca.key;
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';

    ssl_verify_client off;
    #ssl_client_certificate /etc/nginx/certs/ca.crt;
    #ssl_verify_client on;
    #ssl_verify_depth  3;
    ssl_session_tickets off;

    access_log   /var/log/nginx/accesss.log;
    error_log    /var/log/nginx/error.info info;
    error_log    /var/log/nginx/error.crit crit;
    error_log    /var/log/nginx/error_debug.log debug;

    location / {
        proxy_pass https://me.redirect_to.domain;
        #
        #NTT without key ACLEDA site proxy_ssl_trusted_certificate /etc/nginx/sslcerts/NOUSEKEY.pem;
        proxy_ssl_verify              off;
        #
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X_FORWARDED_PROTO https;

        proxy_redirect   off;

        #proxy_set_header Host $http_host;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-NginX-Proxy true;
        # NTT 20210901
        proxy_buffering                     off;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }

}

I think nginx no isssue, when I call from postman okay.
Similar, I see server nginx have handshake hello.

![image](https://user-images.githubusercontent.com/14333403/215934236-525c851f-dabb-4b9d-9b7e-6f6bf54679aa.png)

and I have try some key ca.key -> ca_rsa.key -> ca.crt but not success... 

## client_rsa_init.key -> client.key (curl --key client.key) -> client.csr -> client.crt (curl --cert client.crt) (client.csr, ca.crt, ca_rsa.key)
printf 12345 > client_passphrase.txt
openssl genrsa -des3 -passout file:client_passphrase.txt -out client_rsa_init.key 2048
openssl rsa -passin file:client_passphrase.txt -in client_rsa_init.key -out client.key
openssl req -new -key client.key -subj "/CN=*.mask.domain" -out client.csr

##Sign the certificate with the certificate authority
openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca_rsa.key -set_serial 01 -out client.crt

**Comment by nguyentthai96** [comment]
I have try more solution general key
## ca.key -> ca_rsa.key -> ca.crt (ssl_client_certificate)
openssl genrsa -des3 -out ca.key 4096
#Remove passphrase for example purposes
openssl rsa -in ca.key -out ca_rsa.key
openssl req -new -x509 -days 3650 -key ca_rsa.key -subj "/CN=*.mask.domain" -out ca.crt

## server.key (ssl_certificate_key) -> server.csr -> server.crt (ssl_certificate) (server.csr, ca.crt, ca_rsa.key)
printf 12345 > passphrase.txt
openssl genrsa -des3 -passout file:passphrase.txt -out server.key 2048
openssl req -new -passin file:passphrase.txt -key server.key -subj "/CN=*.mask.domain" -out server.csr

openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca_rsa.key -set_serial 01 -out server.crt


## client_rsa_init.key -> client.key (curl --key client.key) -> client.csr -> client.crt (curl --cert client.crt) (client.csr, ca.crt, ca_rsa.key)
printf 12345 > client_passphrase.txt
openssl genrsa -des3 -passout file:client_passphrase.txt -out client_rsa_init.key 2048
openssl rsa -passin file:client_passphrase.txt -in client_rsa_init.key -out client.key
openssl req -new -key client.key -subj "/CN=*.mask.domain" -out client.csr

##Sign the certificate with the certificate authority
openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca_rsa.key -set_serial 01 -out client.crt

**Comment by nguyentthai96** [comment]
Curl that have response okay
curl --key client.key \
--cert client.crt \
--location --request POST 'https://me.mask.domain/api/v1/function' --insecure \
--header 'Content-Type: application/json' \
--data '{"username":"<mask>","password":"<mask>","client_id":"third_party","client_secret":"<mask data>"}'

**Comment by nguyentthai96** [comment]
Thank you so much, great support, now I resolve that issue, I need accept server public certificate file to JVM or Java code (.withTrustMaterial(trustManager)) / application (browser)
keytool -import -noprompt -trustcacerts -alias myFancyAlias -file /path/to/my/cert/myCert.cer -keystore /path/to/my/jdk/jre/lib/security/cacerts/keystore.jks -storepass changeit

https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore
 https://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server

Best tools:  https://github.com/Hakky54/certificate-ripper.

**Comment by Hakky54** [comment]
Awesome, great to hear it worked for you. The alternative of adding the server certificate to the jdk cacert is also a nice one. Good luck with it and feel free to open a new issue if needed
