### ISSUE TITLE
Method names withDefaultTrustMaterial vs withSystemTrustMaterial

### ISSUE THREAD

**Issue by EugenMayer** [Hakky54/sslcontext-kickstart#309]
Currently (at least for me suprisingly) those methods mean this semantically (under linux at least)

`withDefaultTrustMaterial` adds the default for the system ca store, under linux e.g. `ca-certificates` which lets you validate officially signed certificates

`withSystemTrustMaterial` adds the support for OS bases keystores of the user to expand the validation with custom imported certificates. For linux, there is no standard keystore (unless you use android).

Iam not sure what `withDefaultTrustMaterial` does under macos/windows, i assume that `withSystemTrustMaterial` under macos actually adds the ability to validate official certificates AND custom certificates.

My suggestion would be to fill up what we know about those methods for each os and then reconsider, if the naming still fits or even if it is very much OS specific.

- MacOS: IMHO `withDefaultTrustMaterial` does nothing under macos, `withSystemTrustMaterial` adds support for official and custom cert validation
- Linux: `withDefaultTrustMaterial` adds support for official certificates, while `withSystemTrustMaterial` does nothing
- Android: IMHO `withDefaultTrustMaterial` adds support for official certificates, while `withSystemTrustMaterial` does add special android certificates (not sure about both).
- Windows: TBA

The inverse behavior for Linux/MacOS is what concerns me. It's a tripwire i would say

**Comment by Hakky54** [comment]
The name might be confusing without some context, but I thought the readme would be sufficient to explain the usage of it.

See here: https://github.com/Hakky54/sslcontext-kickstart#loading-jdk-and-os-trusted-certificates
DefaultTrustMaterial refers to the trusted certificates which the JDK provides. So any application runs on a Java Runtime Environment and that environment is bundled with trusted certificates by Oracle or any other company which provided a JDK. It can also be access on the files system see your java home path under lib\security. I named it default as the name should be self explaining as every jdk has been bundled with default list of trusted certificates/ca.

Next to the one which jdk provides some operating systems can also provide trusted certifciates which can easily be accessed within java without the need of writing explicitly IO related code. I named it system trust material as it refers to the OS. As far as I know Windows, Mac and Android have a specialized keystore type which can be used to load those trusted certicates such as: Windows-ROOT, Windows-MY, KeychainStore, AndroidCAStore. I think you have already seen the source code, but I am linking it here for others who might read this issue: https://github.com/Hakky54/sslcontext-kickstart/blob/0b645763631541b38011c73794502de1b241914f/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/KeyStoreUtils.java#L198

So my initial implementation is using a specialized keystore type which provide the trusted certificates, however Linux does not have something like that. But it has a bunch of trusted certificates under the directory `/usr/local/share/ca-certificates/` which can be access and loaded. So in my opinion we can improve the loading mechanisme for linux trusted certificates by reading that directory and loading all the certificates. Would you like to create a pull request?

**Comment by EugenMayer** [comment]
I think we have a misunderstanding here (or i'am confused). AFAIU withDefaultTrustMaterial does already use the system certificates under linux. Am i wrong with that?

**Comment by Hakky54** [comment]
So do you still think it is confusing with this context? Not quite sure whether I was clear with my explanation.
But I still want to improve the loading of the linux certificates, but I was not quite sure whether you wanted that too?

**Comment by Hakky54** [comment]
By the way, you can also fork the project and run it locally. The unit test demonstrates this use case, see here:
https://github.com/Hakky54/sslcontext-kickstart/blob/0b645763631541b38011c73794502de1b241914f/sslcontext-kickstart/src/test/java/nl/altindag/ssl/SSLFactoryShould.java#L517

If you debug it you will see a bunch of trusted certificates, see below for the results which I am getting:
<img width="2048" alt="Screenshot 2023-04-13 at 14 07 10" src="https://user-images.githubusercontent.com/16032204/231753449-fb6599ce-8549-48e0-948f-9ce99d56c877.png">

**Comment by Hakky54** [comment]
> Since it has yet not been implemented for linux, it does not add anything but yet throw a warning.

Yes, in that way when someone is running it on linux I just wanted to inform them that it will do nothing for linux. The warn message informs the developer but it is not a blocking issue for the flow.

> What is your take on this?

I am not sure whether there is a huge difference in the path of where the trusted certificates are located for all of the distrubtions. But if it is even 50% of the cases located under `/usr/local/share/ca-certificates/` than it might be worth to support it. We can then further enhance it with additional paths to lookup and validate whether the path exists and get all certificates if they exists. I will further investigate it and make a draft

**Comment by Hakky54** [comment]
Hi @EugenMayer I drafted a pull request, see here: https://github.com/Hakky54/sslcontext-kickstart/pull/310

You can try it out on your linux machine to see whether it is behaving like expected. I still need to setup a linux environment to try it out. Please ping me when you have your test results. I am curious if this actually works

**Comment by EugenMayer** [comment]
> You can try it out on your linux machine to see whether it is behaving like expected. I still need to setup a linux environment to try it out. Please ping me when you have your test results. I am curious if this actually works

Simply use docker for that - also in the CI. A simple docker based setup can help test drive this implementation. If you like, even run a test matrix for deb/alpine/fedora or at least pick one

**Comment by Hakky54** [comment]
The linked pull request has been merged which contains the improved mechanisme to fetch the OS certificates for Mac and Linux, I reopened this issue because there was still a pending PR from @EugenMayer but you created a new issue related to those changes in here https://github.com/Hakky54/sslcontext-kickstart/issues/316 so this issue can be closed as it is resolved. Looking forward to your PR!
