### ISSUE TITLE
New System Keystores in Windows

### ISSUE THREAD

**Issue by jenspopp** [Hakky54/sslcontext-kickstart#356]
With Java 11.0.18 and 17.0.5 a long standing issue (https://bugs.openjdk.org/browse/JDK-6782021) with Windows-MY was solved. This includes the introduction of new keystore types in SunMSCAPI 

From: https://bugs.openjdk.org/browse/JDK-8286790

The Windows KeyStore support in the SunMSCAPI provider has been expanded to include access to the local machine location. The new keystore types are:

* "Windows-MY-LOCALMACHINE"
* "Windows-ROOT-LOCALMACHINE"

The following keystore types were also added, allowing developers to make it clear they map to the current user:

* "Windows-MY-CURRENTUSER" (same as "Windows-MY")
* "Windows-ROOT-CURRENTUSER" (same as "Windows-ROOT")

Perhaps it could be generated automatically from something like:

        try {
            final Provider p = Security.getProvider("SunMSCAPI");
            for(final Enumeration e = p.keys(); e.hasMoreElements();) {
                final String name = e.nextElement().toString();
                if (name.startsWith("KeyStore.")) {
                    System.out.println(name.substring(9));
                }

                }
        } catch (final Exception e) {
            System.out.println(e);
        }

Which returns in Java 11/17

Windows-MY-CURRENTUSER
Windows-MY-LOCALMACHINE
Windows-ROOT-LOCALMACHINE
Windows-ROOT-CURRENTUSER
Windows-ROOT
Windows-MY

Could this be added in the KeyStoreUtils.loadSystemKeyStores() ? The new Windows-MY-LOCALMACHINE is very useful for services that run on ACME certificates published automatically to the store (e.g. with win.acme)

**Comment by Hakky54** [comment]
Thank you for this detailed description and reference to the links of openjdk. It seems like a nice addition to this library to provide those keystores out of the box within the method `KeyStoreUtils .loadSystemKeyStores()`

I have created a PR and it works, see here: https://github.com/Hakky54/sslcontext-kickstart/pull/357
Please have a look at the PR, if you think something is missing I can still add it.

Here is a printscreen from one of the tests of the build:

<img width="1055" alt="Screenshot 2023-06-19 at 22 20 36" src="https://github.com/Hakky54/sslcontext-kickstart/assets/16032204/c174dcf8-04c2-4bff-8ef0-9d6fdcdb7dec">

**Comment by jenspopp** [comment]
Yes, at least at a short test it works for me. Also tested good under earlier JDK versions. Log debug for failed types is also good for me, since I have many projects still running on JDK 8 and many error or warnings would cause confusion ;-)

**Comment by Hakky54** [comment]
Thank you for confirming on your side that it is also working. 

> Log debug for failed types is also good for me, since I have many projects still running on JDK 8 and many error or warnings would cause confusion ;-)

Great! Any exception will be ignored and also not printed. The end-user will be only informed in their logs if debug is enabled. So on Java 8 if you don't want those debug messages, you can just turn it of.

I merged it by the way, I will make a release somewhere this week. I will update you when it is done.

**Comment by Hakky54** [comment]
It is released today and available from version `8.1.2` onwards. Enjoy! 🚀
