### ISSUE TITLE
MacCertificateUtils: Invoke "security" without the need of a shell

### ISSUE THREAD

**Issue by thahnen** [Hakky54/sslcontext-kickstart#369]
## Summary

In `MacCertificateUtils.createProcess(String)` (see [HERE](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/MacCertificateUtils.java#L94-L103)), in order to get the installed certificates via running the macOS-specific command *security*, a shell is spawned to handle running the command. This should not rely on a shell as an additional layer and rather invoke the command at `/usr/bin/security` directly.

## Related problem(s)

We're using the library internally for SonarLint and we got the information that it seems to be flagged by some antivirus software as potential secret theft (maybe due to the fact that it is handled via the shell, but I cannot say so and I'm only guessing on that side, mentioned by @nquinquenel in #367) or at least some warning is thrown.
Nevertheless, if it is connected to the issue or not, the shell layer should be avoided if possible.

**Comment by Hakky54** [comment]
Hi @thahnen 

Amazing to discover that the antivirus is raising alerts. Thank you for sharing your thoughts and giving idea's to resolve it. I have created a branch, see here for the PR: https://github.com/Hakky54/sslcontext-kickstart/pull/370 I replaced the shell call with a different method and it is working!

Would it be possible for you to create a snapshot locally from that branch and test it out on your side to see if the antivirus is giving the same flags or alerts?

**Comment by thahnen** [comment]
Hi @Hakky54,

yeah, I'll try on my side. Please give me some time for testing and I'll get back to you at last at the end of the week!

Best,
Tobias

**Comment by thahnen** [comment]
Hi @Hakky54,

I'm sorry but due to sickness, this will take a few days longer for me than expected. Just wanted to inform you as I did not reply yet.

**Comment by Hakky54** [comment]
@thahnen as discussed in the other channel the code changes within the pull requests seems te resolve the issues you had faced. I have merged the PR and I will make a release this evening. I will keep you up-to-date regarding the release

**Comment by Hakky54** [comment]
This fix is now available in version 8.1.6 which is just now released
