### ISSUE TITLE
Add Support For `withoutProtocols` + `withoutCiphers`

### ISSUE THREAD

**Issue by ssmoss** [Hakky54/sslcontext-kickstart#432]
So it seems one can select which protocols and ciphers to use by doing the following:
```java
SSLFactory.builder()
          .withProtocols("TLSv1.3", "TLSv1.2")
          .withCiphers(
                    "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
                    "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                    ...
          )
          ...
```

Would it be possible to support excluding both protocols and ciphers as well:
```java
SSLFactory.builder()
          .withoutProtocols("SSLv3")
          .withoutCiphers(
                    "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA",
                    "SSL_DHE_DSS_WITH_DES_CBC_SHA",
                    ...
          )
          ...
```
The idea would be it takes the default protocols and ciphers and remove the ones specified in without. When both are used which might be a little weird, it would remove the without from the with ones.

Please let me know thoughts on this idea or if there is an existing / better way to do this.

**Comment by Hakky54** [comment]
Hi @ssmoss I like the idea. I have created PR, see here: https://github.com/Hakky54/sslcontext-kickstart/pull/433
Please have a look at it. If you don't have any remarks I will merge it.

**Comment by ssmoss** [comment]
Nothing jumps out at me. Glad you like the idea and thanks for adding it :)

**Comment by Hakky54** [comment]
@ssmoss I just made a release today, version `8.3.0` which includes these exclusion options for ciphers and protocols. Enjoy the change!
