### ISSUE TITLE
When using pem utils v8.2.0 dependency in android, Duplicate class error in org.bouncycastle

### ISSUE THREAD

**Issue by mugheesakram** [Hakky54/sslcontext-kickstart#435]
**Describe the bug**
Hi, I am working on Certificate pinning and came across your library. After reading through the documentation, I decided to use PemUtils Dependency. But, when I am compiling my code, it is giving me error:
<img width="1510" alt="Screenshot 2024-01-12 at 11 36 38 AM" src="https://github.com/Hakky54/sslcontext-kickstart/assets/24847601/ae4078ff-3823-4c96-865b-9a895ab0a9c2">

I have also tried to exclude or pickfirst the latest version of org.bouncycastle in the packaging option but not working.

**Comment by Hakky54** [comment]
I recently updated bouncy castle to resolve a transitive vulnerability see here for the details: https://github.com/Hakky54/sslcontext-kickstart/issues/387

The message which you are getting is saying that you have 2 jars in your class path which have identical classes with identical package name.

The solution would be excluded one or the other dependency. Can you try to exclude any of the conflicting dependency?

If it won't resolve I can further help, but then I also need your dependency tree here.
