### ISSUE TITLE
Implementing Dynamic SSL Pinning Using Base64 Encoded Server Certificate?

### ISSUE THREAD

**Issue by praveenathuru** [Hakky54/sslcontext-kickstart#455]
**Describe the bug**
I'm looking for a way to implement dynamic SSL pinning in my application. The server provides the certificate in Base64 encoded format, and I want to ensure that my application only trusts this certificate.

I've explored various options, but I'm unsure about the best approach. Can anyone provide guidance or suggest a method to achieve dynamic SSL pinning using the provided Base64 encoded server certificate?

**Additional Information**:

The certificate is not stored locally within the application.
I'm seeking a solution that allows the application to trust only the certificate provided by the server.

**Comment by Hakky54** [comment]
This library does not support certificate pinning yet, but it should not be that difficult to add it. I know that okhttp client has built in SSL pinning support, have you considered that maybe? So if you are in a hurry then you can give okhttp a try as they have it already or else I expect to build it here in maybe a week.

**Comment by praveenathuru** [comment]
@Hakky54 I'm considering using OkHttp client for my application, but I have a few questions before that about the library capabilities:
1. Is there a utility available to use a Base64 encoded string (certificate) directly with the SSL socket factory or provide a trust manager based on this certificate?
2. Since OkHttp certificate pinner requires SHA/hash, is there any utility available that can provide the hash to use with it?
3. Is there a way to enforce the use of a custom certificate exclusively, so that the application does not accept system or public certificates available on the device?

I'm planning to implement these features in my application, so I'm wondering if the library can provide the above functionalities.

**Comment by Hakky54** [comment]
Let me try to answer your questions:

> 1. Is there a utility available to use a Base64 encoded string (certificate) directly with the SSL socket factory or provide a trust manager based on this certificate?
This library has actually, but it depends on what the content is of the base64 encoded string. Can you provide an example here of the base64 encoded string? This library can handle pem files, single line pem files, see here for couple of examples: https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#loading-pem-files-from-string-content

> 2. Since OkHttp certificate pinner requires SHA/hash, is there any utility available that can provide the hash to use with it?
To be honest, I am not familar with the pinning and sha hashes at all. And I am also not yet familar how okhttp is dealing with it. I need to go through their source code to understand it.

> 3. Is there a way to enforce the use of a custom certificate exclusively, so that the application does not accept system or public certificates available on the device?
Yes, that is possible. Just get the leaf certificate of the server, so not the intermediate and also not the root ca, and add that to the truststore of the client. Configure your client with just only that trusted certificate and you should ready to go.

**Comment by praveenathuru** [comment]
Great, thanks for your help. just one more doubt here. 
Even I'm not much more familiar with the SSL pinning, what I understood so far is either we should add certificate to the SSL factory or use Okhttp client pinning. I'm just wondering that the idea behind these two different functionalities should be same. If it is so..
1. I'll plan this library to generate certificate file using Base64 encoded content and get hash from it and use it in okhttp pinning. 
2. If that's not the case then I'll use the library SSL context into okhttp client to use SSL pinning.

**Comment by Hakky54** [comment]
I think with ssl pinning the client will do additional checks like checking some parts of the public key info, but I am not sure to be honost as I have not worked on ssl pinning before.

I don't think you need ssl pinning if you only trust the leaf certificate of the server. So don't use the intermediate certificate and also not the root-ca, just only the leaf certificate. That kind of setup is already secure in my opinion. The downside is that you might need to update the trusted certificate everytime in your client when the server has a new certificate.

You can use [certificate-ripper](https://github.com/Hakky54/certificate-ripper) to get the leaf certificate: 
```
crip export der -u=https://github.com
```

Replace github.com with your server. It will write the files to your file system. Get the first one and configure SSLFactory with that certificate. Please give it a try and feel free to ping me when you need help. To use the der certificate you can view this documentation: https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#using-der-files

The SSLFactory has the properties to configure okhttp. I happen to have an example here: https://github.com/Hakky54/mutual-tls-ssl/blob/35cba2f3a2dcd73b01fa323b99eec7777f7429bb/client/src/main/java/nl/altindag/client/ClientConfig.java#L125

**Comment by praveenathuru** [comment]
Thankyou for your kind help @Hakky54
