### ISSUE TITLE
PKIX path building failed (client-side) when using certificates from Let's Encyrpt

### ISSUE THREAD

**Issue by e3ndr** [Hakky54/sslcontext-kickstart#457]
**Describe the bug**
I've had this issue before when trying to implement PEM loading myself. Basically, browsers will happily accept the connection but Java and some other languages will fail to connect.

**To Reproduce**
1. Issue yourself a certificate for a test domain, I used win-acme.
2. Create a SSL TCP server using the below code: 

```java
X509ExtendedKeyManager keyManager = PemUtils.loadIdentityMaterial(Paths.get("ssl/crt.pem"), Paths.get("ssl/key.pem"));
X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial(Paths.get("ssl/chain.pem"));

SSLFactory factory = SSLFactory.builder()
    .withDefaultTrustMaterial()
    .withIdentityMaterial(keyManager)
    .withTrustMaterial(trustManager)
    .build();

try (ServerSocket sock = factory.getSslServerSocketFactory().createServerSocket(8080)) {
    while (true) {
        try (Socket client = sock.accept()) {
            client.getOutputStream().write(
                ("HTTP/1.1 200 OK\r\n"
                    + "Content-Type: text/plain\r\n"
                    + "Content-Length: 13\r\n"
                    + "\r\n"
                    + "Hello, World!").getBytes()
            );
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
3. Use something like [SSLPoke](https://github.com/MichalHecko/SSLPoke) to try to connect to the server (`java -jar SSLPoke.jar SOMEDOMAIN PORT`) to test the connection.
4. Observe that `javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown` is thrown on the Server, and `javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` on SSLPoke/other Java clients but will succeed in a browser.

**Expected behavior**
It shouldn't fail :P

**Screenshots**
Works fine in a browser:
![opera_RiMLOeXM4X](https://github.com/Hakky54/sslcontext-kickstart/assets/33337309/c46f7f0b-f1f0-47e6-993f-a6deaf5e286e)

**Environmental Data:**

Server:
 - Java Version: Temurin-17
 - Maven Version: Unsure, whatever's bundled with Eclipse
 - OS: Windows

SSLPoke:
 - Java Version: Temurin-17
 - Maven Version: N/A
 - OS: Windows

**Additional context**
These same certificates work fine when loaded properly into a Java keystore. [Here's](https://gist.github.com/e3ndr/f55cf1abd67db258396c645862e98a13) the script I use to do that.

**Comment by Hakky54** [comment]
I have tried it on my side and it works fine with SSLPoke. Can you maybe share your pem files? In that way I can replicate the exact situation as you have.

**Comment by e3ndr** [comment]
Did you generate them with Win ACME? That could be the issue. I'll generate some and make a throwaway subdomain in the morning :)

**Comment by Hakky54** [comment]
I noticed you mentioned explicitly certificates which have been issued with win-acme, however I don't have that kind of setup in place. I tried with self-signed certificate which has been signed by a custom root-ca from my tutorial here https://github.com/Hakky54/mutual-tls-ssl?tab=readme-ov-file#two-way-tls-based-on-trusting-the-certificate-authority

I had the feeling that it should be similar to the one of win-acme, but we will find out if you can provide me some throwaway files. Can you configure the certificateds with subject alternative name localhost? In that way I will be able to use it locally.

**Comment by e3ndr** [comment]
Would you mind trying a Let's Encrypt certificate? There's also the acme.sh client which works on *nix. Currently not at my Windows computer otherwise I would generate a cert :P

**Comment by Hakky54** [comment]
Yes, I would like to try with a let's encrypt certificate. Can you please provide one?

**Comment by e3ndr** [comment]
Here you go. This certificate is issued for `sslcontext-kickstart-i457.e3ndr.xyz` and `*.sslcontext-kickstart-i457.e3ndr.xyz`, which is similar to my production domain.

[sslcontext-kickstart-i457.e3ndr.xyz.zip](https://github.com/Hakky54/sslcontext-kickstart/files/14256245/sslcontext-kickstart-i457.e3ndr.xyz.zip)

**Comment by e3ndr** [comment]
Oh, and those domains are pointed to `127.0.0.1` for local testing ;)

**Comment by Hakky54** [comment]
Thank you for taking the effort of generating the files! I really appreciate it. 
I tried with pem files which you have provided and it works. See the code snippet below:

```java
import nl.altindag.ssl.SSLFactory;
import nl.altindag.ssl.pem.util.PemUtils;

import javax.net.ssl.X509ExtendedKeyManager;
import javax.net.ssl.X509ExtendedTrustManager;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App {

    public static void main(String[] args) {
        X509ExtendedKeyManager keyManager = PemUtils.loadIdentityMaterial("chain.pem", "key.pem");
        X509ExtendedTrustManager trustManager = PemUtils.loadTrustMaterial("crt.pem");

        SSLFactory factory = SSLFactory.builder()
                .withIdentityMaterial(keyManager)
                .withTrustMaterial(trustManager)
                .build();

        try (ServerSocket sock = factory.getSslServerSocketFactory().createServerSocket(8080)) {
            while (true) {
                try (Socket client = sock.accept()) {
                    client.getOutputStream().write(
                            ("HTTP/1.1 200 OK\r\n"
                                    + "Content-Type: text/plain\r\n"
                                    + "Content-Length: 13\r\n"
                                    + "\r\n"
                                    + "Hello, World!").getBytes()
                    );
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
```

I compared this code snippet with your initial code snippet from your first post and I think I see the root cause of your issue.
You have configured the chain.pem as trustmaterial and crt.pem combined with the key.pem as identitymaterial. The chain.pem and key.pem needs to be loaded as identity material and the crt.pem as trustmaterial. Can you give another try on your side?

**Comment by e3ndr** [comment]
Oh that was it. Damn, guess I misread the documentation. Thanks for all the help!
