### ISSUE TITLE
FTPs - None of the TrustManagers trust this certificate chain

### ISSUE THREAD

**Issue by austinarbor** [Hakky54/sslcontext-kickstart#466]
**Describe the bug**
When using the (new) Security provider with commons-net FTPSClient, I am getting the exception stacktrace below. In this case a self-signed certificate is being used, but it is **not** added to the system certificates or the `cacerts` file. _However_, if I skip setting the security provider, everything works as expected...so I don't think any custom certificate settings should be required for it to work either - to be honest I have no idea how it works out of the box without any custom certificate settings.

**Code**
```java
var factory = SSLFactory.builder().withDefaultTrustMaterial().withSystemTrustMaterial().build();
var provider = ProviderUtils.create(factory);
Security.insertProviderAt(provider, 1); // removing this prevents the exception
SSLContext.setDefault(factory.getSslContext());
FTPSClient client = new FTPSClient();
InetAddress inetAddress = InetAddress.getByName(host);
client.connect(inetAddress, port);
```

If I create the factory with `.withTrustingAllCertificatesWithoutValidation()`, everything also succeeds - however, I'm not sure why this option is required if the certificates are accepted by the default `cacerts` file. Is the `checkTrusted` method doing extra validation that's not necessarily done by default?

I've attached two files:
1. `with-provider.txt` sets the security provider and causes the issue - the stacktrace is near the bottom
    1. I did notice that on line 106 of this file the socket seems to get closed - not sure if that's related to the problem
3. `without-provider` does not set the security provider and successfully connects

**Environmental Data:**
 - Java Version: 17.0.9
- OS (Windows/Linux/MacOS): Linux AL2 (also reproduces on OSX)

[with-provider.txt](https://github.com/Hakky54/sslcontext-kickstart/files/14592266/with-provider.txt)
[without-provider.txt](https://github.com/Hakky54/sslcontext-kickstart/files/14592268/without-provider.txt)

**Comment by austinarbor** [comment]
@Hakky54 thanks for the detailed response, as always! I actually just left for vacation until Monday so I won't be able to give it another try until then - you can close this now if you want and I can re-open if I find any issues. Sorry for not looking into the default behavior of commons-net closer, I should have been able to track that down myself and saved you the time!

**Comment by Hakky54** [comment]
Sure, no worries. Enjoy your vacation! Feel free to reopen if the issue is still present.
