### ISSUE TITLE
LoggingX509ExtendedTrustManager should log CertificateException 

### ISSUE THREAD

**Issue by maxxedev** [Hakky54/sslcontext-kickstart#501]
**Is your feature request related to a problem? Please describe.**
[LoggingX509ExtendedTrustManager](https://github.com/Hakky54/sslcontext-kickstart/blob/cb5edd6dfea8edf9a120c1fede1abcc860a36698/sslcontext-kickstart/src/main/java/nl/altindag/ssl/trustmanager/LoggingX509ExtendedTrustManager.java#L37) should log CertificateException thrown by the delegate.

**Describe the solution you'd like**
Apply try/catch to each delegate call and log the exception. Log message should include brief detail of the certificate like CN

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Hakky54** [comment]
Hi @maxxedev thank you for requesting for more detailed logging. I have created a PR, can you have a look at it whether this is ok for you. See here for the PR: https://github.com/Hakky54/sslcontext-kickstart/pull/505

**Comment by maxxedev** [comment]
Thanks for the quick PR. I made a comment in PR

**Comment by Hakky54** [comment]
This is now available in version 8.3.6
