### ISSUE TITLE
Latest patch version contains a breaking change for httpclient<5.4

### ISSUE THREAD

**Issue by richardtippl-ext90046** [Hakky54/sslcontext-kickstart#574]
**Describe the bug**
As covered in #560 and #561, version 8.3.7 has been released with support for new apache httpclient 5.4.
However, the new method has been added to the same class that contains methods supporting older httpclient versions.

When using library with a project that contains an older version of apache httpclient (current version of Spring Boot provides 5.3.1), classloader crashes upon loading of `Apache5SslUtils` because `TlsSocketStrategy` does not exist on the classpath.

This change makes the release a breaking change, which drops support for older versions of httpclient.

**To Reproduce**
1. Add this library to a project which uses httpclient 5.3.1
2. Call `Apache5SslUtils.toSocketFactory(sslFactory)`

**Expected behavior**
A valid `SocketFactory` is returned

**Actual result**
Classloader crash:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/ssl/TlsSocketStrategy
	at <redacted>(<redacted>.java:70)
	at <redacted>$$SpringCGLIB$$0.CGLIB$<redacted>$2(<generated>)
	at <redacted>$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
	at <redacted>$$SpringCGLIB$$0.<redacted>(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
	... 143 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 152 common frames omitted
```
I've redacted any of our classes or method names, however line 70 where the crash happened is where `Apache5SslUtils.toSocketFactory(sslFactory)` is called. The new method `toTlsSocketStrategy` is NOT called.

**Comment by Hakky54** [comment]
Clear, I will investigate this issue. I will revert to you by the end of this week. Can you maybe share the list of dependencies you are using? I saw cglib in the stacktrace, so it might be related to that

**Comment by Hakky54** [comment]
By the way, have you considered also bumping apache http cliënt to version 5.4?
You can easily add that in the maven dependency management section and your issue will also be resolved.

**Comment by richardtippl-ext90046** [comment]
Do you one better. I have a created a minimal example while still keeping the same library versions.

To avoid uploading the whole thing, here is the recipe:
1. Generate a spring boot project with the following [configuration](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.3.4&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web) (a config share link)
2. Add the following lines to pom.xml
```xml
<dependency>
	<groupId>org.apache.httpcomponents.client5</groupId>
	<artifactId>httpclient5</artifactId>
</dependency>

<dependency>
	<groupId>io.github.hakky54</groupId>
	<artifactId>sslcontext-kickstart</artifactId>
	<version>8.3.7</version>
</dependency>

<dependency>
	<groupId>io.github.hakky54</groupId>
	<artifactId>sslcontext-kickstart-for-apache5</artifactId>
	<version>8.3.7</version>
</dependency>
```
3. Add the following to the main method with the requisite imports
```java
SSLFactory.Builder sslFactoryBuilder = SSLFactory.builder()
		.withDefaultTrustMaterial()
		.withSystemTrustMaterial();

SSLFactory sslFactory = sslFactoryBuilder.build();

LayeredConnectionSocketFactory socketFactory = Apache5SslUtils.toSocketFactory(sslFactory);
```
4. Compile and start the main
This leads to a simpler stacktrace of
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hc/client5/http/ssl/TlsSocketStrategy
	at com.example.demo.DemoApplication.main(DemoApplication.java:20)
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 1 more
```

This would be reproduceable in a simple non-spring boot application, using it here simply because it provides dependency management for the libraries we care about. Cglib involvement is within spring boot internals, which is now bypassed as well.

---

RE: Bumping httpclient to version 5.4

Yes, this would be a "solution", however for httpclient we are using a version provided with Spring Boot, which guarantees compatibility, there have been some large changes in httpclient minor version bumps before and upgrading without maitaining the compatibility matrix with Spring could be dangerous in other ways. :)

New version will probably be included in Spring boot 3.4 or 3.5 so upgrading will come with that.

**Comment by Hakky54** [comment]
I was able to reproduce it on my side. Indeed you are right as it throws a runtime exception as a class from Apache is absent because of the older version. This is unfortunately not fixable as you cannot have the latest version of this library specific to apache while using an older version of apache itself. 

I don't think it is a bad thing to stay at version 8.3.6 for now as I am not planning to add new features soon. So you wont be missing out new features. Next to that the library is stable for quite some time already.

In Q1/Q2 of 2025 I am planning to remove deprecated methods and release a major version 9.x.x and I hope you can then hop along if Spring developers have also bumped Apache Client 5 in Spring Boot on their side as well.

As stated ealier I cannot fix this issue as it is just related to an external library related to a specific version. So my suggestion is to stay for now at 8.3.6 till you you can bumped Spring Boot alongside with Apache Client 5 with this library. What do you think?

**Comment by richardtippl-ext90046** [comment]
I guess this is more about what you're willing to accept as the developer. A patch version should not introduce a breaking change, also the readme makes it seem the library works with Apache Httpclient 5*, so i feel you need to specify only the newest 5.4+ works.

IMO the correct course of action of supporting it would sadly have to be a separate util class for 5.4 which would alleviate the classloading issues, and then cleaning it up when dropping support for older versions with a major version change. (this change would also break support for anyone who already updated to 8.3.7)

Dropping support for older versions of a library is of course fine, I just feel it should be accompanied by the relevant major version increase, in addition to maybe a compatibility matrix in the readme, not during a patch version meant for bugfixes.

However as you say, i can live with it, we can mute dependabot for now and just ignore the version update.

**Comment by Hakky54** [comment]
Indeed a patch version should not introduce a breaking change however, I didn't do it intentionally. I didn't expect this side effect to be honest. 

> IMO the correct course of action of supporting it would sadly have to be a separate util class for 5.4 which would alleviate the classloading issues, and then cleaning it up when dropping support for older versions with a major version change. (this change would also break support for anyone who already updated to 8.3.7)

I was in doubt whether I should do this or advise you to stay at 8.3.6

> Dropping support for older versions of a library is of course fine, I just feel it should be accompanied by the relevant major version increase, in addition to maybe a compatibility matrix in the readme, not during a patch version meant for bugfixes.

Thank you for your suggestion, next time I will test it better and make a major release if this kind of breaking change is occuring again. I appreciate your feedback mate.

> However as you say, i can live with it, we can mute dependabot for now and just ignore the version update.

Thank you for being ok with this option
